# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "sd_mod"
    "rtsx_usb_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [
      "defaults"
      "mode=755"
      "nodev"
      "nosuid"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8569-7289";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/994b5d4e-6b89-4f86-b319-30f476723ff0";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "noatime"
      "compress-force=zstd"
      "space_cache=v2"
    ];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/994b5d4e-6b89-4f86-b319-30f476723ff0";
    fsType = "btrfs";
    options = [
      "subvol=tmp"
      "noatime"
      "compress-force=zstd"
      "space_cache=v2"
    ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/994b5d4e-6b89-4f86-b319-30f476723ff0";
    fsType = "btrfs";
    options = [
      "subvol=persist"
      "noatime"
      "compress-force=zstd"
      "space_cache=v2"
    ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/994b5d4e-6b89-4f86-b319-30f476723ff0";
    fsType = "btrfs";
    options = [
      "subvol=swap"
      "noatime"
      "compress-force=zstd"
      "space_cache=v2"
    ];
  };

  swapDevices = [ { device = "/swap/swapfile"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
